# Generated by Django 5.2.7 on 2026-03-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0002_todaydeals'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaydeals',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
