# Generated by Django 5.2.7 on 2026-03-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0004_toppicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='deal_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
    ]
