# Generated by Django 5.2.7 on 2026-03-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0005_deal_all'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='toppicks',
            new_name='h_todaydeals',
        ),
        migrations.RenameModel(
            old_name='todaydeals',
            new_name='h_toppicks',
        ),
    ]
