# Generated by Django 5.2.7 on 2026-03-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0006_rename_toppicks_h_todaydeals_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='h_todaydeals',
            new_name='todaydeals',
        ),
        migrations.RenameModel(
            old_name='h_toppicks',
            new_name='toppicks',
        ),
    ]
