# Generated by Django 5.2.7 on 2026-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0009_d_electronic_d_fashion_d_fitness_deal_10000_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='b_fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('title', models.CharField(max_length=200)),
                ('decription', models.CharField(max_length=200)),
            ],
        ),
    ]
