# Generated by Django 5.2.7 on 2026-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0011_b_funny_b_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='d_pickup_x1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/')),
                ('name', models.CharField(max_length=200)),
                ('decription', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('oldprice', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
    ]
