# Generated by Django 5.2.7 on 2026-03-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0012_d_pickup_x1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_pickup_x1',
            name='title',
        ),
    ]
