# Generated by Django 5.2.7 on 2026-03-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0013_remove_d_pickup_x1_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deal_3000',
            new_name='d_mobile',
        ),
        migrations.DeleteModel(
            name='deal_10000',
        ),
        migrations.DeleteModel(
            name='deal_100000',
        ),
        migrations.DeleteModel(
            name='deal_1499',
        ),
        migrations.DeleteModel(
            name='deal_20000',
        ),
        migrations.DeleteModel(
            name='deal_299',
        ),
        migrations.DeleteModel(
            name='deal_499',
        ),
        migrations.DeleteModel(
            name='deal_5000',
        ),
        migrations.DeleteModel(
            name='deal_50000',
        ),
        migrations.DeleteModel(
            name='deal_899',
        ),
    ]
