# Generated by Django 5.2.7 on 2026-03-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0015_d_appliances_d_beauty_d_food_d_furniture_d_kitchen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_fitness',
            name='decription',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='b_fitness',
            name='title',
            field=models.CharField(max_length=52),
        ),
    ]
