# Generated by Django 5.2.7 on 2026-03-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0017_all_fitness_all_funny_all_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_fitness',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
