# Generated by Django 5.2.7 on 2026-03-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0018_b_fitness_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_fitness',
            name='text',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='all_funny',
            name='text',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='all_news',
            name='text',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='b_funny',
            name='text',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='b_news',
            name='text',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='b_fitness',
            name='text',
            field=models.TextField(default='No description'),
        ),
    ]
