# Generated by Django 5.2.7 on 2026-04-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0019_all_fitness_text_all_funny_text_all_news_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_todaydeals',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='h_toppicks',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
