# Generated by Django 5.2.7 on 2026-04-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0020_alter_h_todaydeals_name_alter_h_toppicks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_fitness',
            name='price',
            field=models.IntegerField(),
        ),
    ]
