# Generated by Django 5.2.7 on 2026-04-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0021_alter_d_fitness_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_appliances',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='d_beauty',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='d_electronic',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='d_fashion',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='d_food',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='d_furniture',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='d_kitchen',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='d_mobile',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='d_toys',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deal_all',
            name='price',
            field=models.IntegerField(),
        ),
    ]
