# Generated by Django 5.2.7 on 2026-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0022_alter_d_appliances_price_alter_d_beauty_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_fashion',
            name='cetegory',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='d_fitness',
            name='cetegory',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
