# Generated by Django 5.2.7 on 2026-04-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0023_d_fashion_cetegory_d_fitness_cetegory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_fashion',
            name='cetegory',
        ),
        migrations.RemoveField(
            model_name='d_fitness',
            name='cetegory',
        ),
    ]
