# Generated by Django 5.2.7 on 2026-04-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0024_remove_d_fashion_cetegory_remove_d_fitness_cetegory'),
    ]

    operations = [
        migrations.CreateModel(
            name='h_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
