# Generated by Django 5.2.7 on 2026-04-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0025_h_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='h_blog',
            new_name='h_blogs',
        ),
    ]
