# Generated by Django 5.2.7 on 2026-04-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0026_rename_h_blog_h_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='h_blogs',
            name='cetegory',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='h_blogs',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
