# Generated by Django 5.2.7 on 2026-04-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0027_h_blogs_cetegory_h_blogs_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_pickup_x1',
            name='decription',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='d_pickup_x1',
            name='name',
            field=models.CharField(max_length=57),
        ),
    ]
