# Generated by Django 5.2.7 on 2026-04-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0028_alter_d_pickup_x1_decription_alter_d_pickup_x1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_pickup_x1',
            name='off',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
