# Generated by Django 5.2.7 on 2026-04-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0029_d_pickup_x1_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal_all',
            name='badge',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
