# Generated by Django 5.2.7 on 2026-04-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0030_deal_all_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_electronic',
            name='badge',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
