# Generated by Django 5.2.7 on 2026-04-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0031_d_electronic_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_appliances',
            name='badge',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='d_beauty',
            name='badge',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='d_fashion',
            name='badge',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='d_fitness',
            name='badge',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='d_food',
            name='badge',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='d_furniture',
            name='badge',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='d_kitchen',
            name='badge',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='d_mobile',
            name='badge',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='d_toys',
            name='badge',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='d_electronic',
            name='badge',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='deal_all',
            name='badge',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
