# Generated by Django 5.2.7 on 2026-04-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0032_d_appliances_badge_d_beauty_badge_d_fashion_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_fitness',
            name='text',
            field=models.CharField(default='No description', max_length=1000000),
        ),
    ]
