# Generated by Django 5.2.7 on 2026-04-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0033_alter_all_fitness_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_fitness',
            name='text',
            field=models.TextField(default='No description'),
        ),
    ]
