# Generated by Django 5.2.7 on 2026-04-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0034_alter_all_fitness_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_funny',
            name='decription',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='all_news',
            name='decription',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='b_funny',
            name='decription',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='b_news',
            name='decription',
            field=models.CharField(max_length=55),
        ),
    ]
