# Generated by Django 5.2.7 on 2026-04-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0035_alter_all_funny_decription_alter_all_news_decription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_funny',
            name='title',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='all_news',
            name='title',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='b_funny',
            name='title',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='b_news',
            name='title',
            field=models.CharField(max_length=52),
        ),
    ]
