# Generated by Django 5.2.7 on 2026-04-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0037_alter_all_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_news',
            name='title',
            field=models.CharField(max_length=65),
        ),
    ]
