# Generated by Django 5.2.7 on 2026-04-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0038_alter_all_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_fitness',
            name='title',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='all_funny',
            name='title',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='b_fitness',
            name='title',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='b_news',
            name='title',
            field=models.CharField(max_length=65),
        ),
    ]
