# Generated by Django 5.2.7 on 2026-04-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0039_alter_all_fitness_title_alter_all_funny_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='h_blogs',
            name='description',
        ),
        migrations.AlterField(
            model_name='h_blogs',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
