# Generated by Django 5.2.7 on 2026-04-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0040_remove_h_blogs_description_alter_h_blogs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_blogs',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
