# Generated by Django 5.2.7 on 2026-04-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0041_alter_h_blogs_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='h_blogs',
            name='link',
        ),
    ]
