# Generated by Django 5.2.7 on 2026-04-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZONEHUB', '0042_remove_h_blogs_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_appliances',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='d_beauty',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='d_electronic',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='d_fashion',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='d_fitness',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='d_food',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='d_furniture',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='d_kitchen',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='d_mobile',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='d_toys',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='deal_all',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
